all:
	python solution.py < input0.txt > my0.txt
	@diff my0.txt output0.txt
	python solution.py < input1.txt > my1.txt
	@diff my1.txt output1.txt
	python solution.py < input2.txt > my2.txt
	@diff my2.txt output2.txt
	python solution.py < input3.txt > my3.txt
	@diff my3.txt output3.txt
	python solution.py < input4.txt > my4.txt
	@diff my4.txt output4.txt
	python solution.py < input5.txt > my5.txt
	@diff my5.txt output5.txt
	python solution.py < input6.txt > my6.txt
	@diff my6.txt output6.txt
clean:
	rm -rf my*.txt
